MyShop/MyShop/Models/Category/Category.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using MyShop;
namespace MyShop
{
    public class Category
    {
        [ScaffoldColumn(false)]
        public int ID { get; set; }

        [Required(ErrorMessage = "*")]
        public string Name { get; set; }

        public int? ParentCategoryId { get; set; }

        public string PictureName { get; set; }

        public string PictureType { get; set; }

        [AllowHtml]
        public string Description { get; set; }

        [Required(ErrorMessage = "*")]
        public string MetaKeyword { get; set; }

        [Required(ErrorMessage = "*")]
        public string MetaDescription { get; set; }

        [Required(ErrorMessage = "*")]
        public string MetaTitle { get; set; }

        //[Required(ErrorMessage = "*")]
        public string PriceRanges { get; set; }

        public bool ShowOnHomePage { get; set; }

        public bool IncludeInTopMenu { get; set; }

        public bool Published { get; set; }

        public bool IsDeleted { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime CreatedOnUtc { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime UpdatedOnUtc { get; set; }

        //public IList<ProductPicture> ProductPicture { get; set; }

    }
}

MyShop/MyShop/Models/Category/CategoryMapping.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using MyShop;
namespace MyShop
{
    class CategoryMapping
    {
        // have to  mapping to product
        // have to mapping with image
        //have to mapping with brand
        //have to mapping with seller
        //have to mapping with review for vendor/product

        //Note: one category have only one product 
        // a product have multiple image,
        // a product have multiple vendor,
        // a product have only brand
        // a product have multiple attribute(product filter title)
        // a attribute have multiple value(product filter value)

        // a product have mulptiple review and a vendor have mulptiple review...


        [Required]
        public int ProductID { get; set; }
        public virtual Product Product { get; set; }

        [Required]
        public int CategoryID { get; set; }
        public virtual Category Category { get; set; }
    }
}

MyShop/MyShop/Models/Category/joinpiccat.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using MyShop;
//using ModelLibrary.Picture;
using G2MFashions.Models.Product;
namespace ModelLibrary.Category
{
    public class joinpiccat
    {
        //public Category Category { get; set; }
        //public Picture.Picture Picture { get; set; }
        //public List<CustomerProduct> CustomerProduct { get; set; }

        //public joinpiccat()//if we have to add data in list variable then we have to initialize the list through constructure
        //{
           
        //    CustomerProduct = new List<CustomerProduct>();

        //}
    }
}

MyShop/MyShop/Controllers/Admin/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ModelLibrary.Category;
using MyShop.Models;
using System.IO;
using System.Data.Entity;
namespace MyShop.Controllers.Admin
{
    public class CategoryController : Controller
    {
        CategoryBindMethod obj = new CategoryBindMethod();
        ApplicationDbContext db = new ApplicationDbContext();
        // GET: Category
        public ActionResult Index()
        {   
            return View(db.Category.ToList());
        }

        public ActionResult Create()
        {   
            ViewBag.ParentCategoryId = obj.CategoryBind();
            return PartialView("Create");
        }

        [HttpPost]
        public ActionResult Create(Category Category, HttpPostedFileBase Image)
        {

            if (System.Web.HttpContext.Current.Request.Files.AllKeys.Any())
            {
                var pic = System.Web.HttpContext.Current.Request.Files["HelpSectionImages"];
            }

            Category.CreatedOnUtc = DateTime.Now;
            Category.UpdatedOnUtc = DateTime.Now;

            if (ModelState.IsValid)
            {
                if (Image != null)
                {
                    Category.PictureName = Image.FileName;
                    Category.PictureType = Image.ContentType;
                }
                if (Category.ParentCategoryId == null)
                    Category.ParentCategoryId = 0;
                
                db.Category.Add(Category);
                db.SaveChanges();
                ViewBag.ResultMessage = "data submitted sucessfully.";
                ModelState.Clear();
                ViewBag.ParentCategoryId = obj.CategoryBind();
                return PartialView("Create");                
            }
            ViewBag.ParentCategoryId = obj.CategoryBind();
            ViewBag.ResultMessage = "Please fill all required fields.";          
            return PartialView("Create");
        }

        public ActionResult EditCategories(int id)
        {
            Category categoryobj = db.Category.Find(id);
        
            List<SelectListItem> CustList = new List<SelectListItem>();
            var Category = db.Category.ToList();
            string CategoryName;
            foreach (var CateId in Category)
            {
                if (CateId.ParentCategoryId != 0)
                {

                    for (int i = 0; i < Category.Count; i++)
                    {
                        if (CateId.ParentCategoryId == Category[i].ID)
                        {
                            CategoryName = Category[i].Name + "<<" + CateId.Name;
                            for (int j = 0; j < Category.Count; j++)
                            {
                                if (Category[i].ParentCategoryId == Category[j].ID)
                                {
                                    CategoryName = Category[j].Name + "<<" + CategoryName;

                                }
                            }
                            if (categoryobj.ID == CateId.ID && CateId.ID != 0)
                            {
                                CustList.Add(new SelectListItem { Text = CategoryName, Value = CateId.ID.ToString(), Selected = true });
                            }
                            else
                            {
                                CustList.Add(new SelectListItem { Text = CategoryName, Value = CateId.ID.ToString() });
                            }
                        }

                    }
                }
                else if (CateId.ParentCategoryId == 0)
                {

                    CategoryName = CateId.Name;
                    if (categoryobj.ID == CateId.ID && CateId.ID != 0)
                    {
                        CustList.Add(new SelectListItem { Text = CategoryName, Value = CateId.ID.ToString(), Selected = true });
                    }
                    else
                    {
                        CustList.Add(new SelectListItem { Text = CategoryName, Value = CateId.ID.ToString() });
                    }
                }
            }



            ViewBag.ParentCategoryId = CustList;

            return PartialView("EditCategories",categoryobj);
        }

        [HttpPost]
        public ActionResult EditCategories(Category cateObj)
        {
            if (ModelState.IsValid)
            {


                if (cateObj.ID != cateObj.ParentCategoryId)
                {
                    cateObj.ParentCategoryId = cateObj.ParentCategoryId;
                }
                else
                {
                    cateObj.ParentCategoryId = db.Category.Where(a => a.ID == cateObj.ParentCategoryId).Select(b => b.ParentCategoryId).FirstOrDefault(); ;
                }
                if (cateObj.ParentCategoryId == null)
                {
                    cateObj.ParentCategoryId = 0;
                }

                db.Entry(cateObj).State = EntityState.Modified;
                db.SaveChanges();
                ViewBag.ResultMessage = "data updated sucessfully.";
                ModelState.Clear();
                return Json(new { message = ViewBag.ResultMessage });

               
            }
            ViewBag.ResultMessage = "Please fill all required fields.";
            return Json(new { message = ViewBag.ResultMessage });
            
        }
    }
}

MyShop/MyShop/Views/Category/Create.cshtml
@model  MyShop.Category




<link rel="stylesheet" href="/assets/plugins/chosen/chosen.min.css" />
<script src="/assets/plugins/chosen/chosen.jquery.min.js"></script>

<script>
    $(document).ready(function () {
        $(".message").hide();

    })
</script>
<style>
    input[type=checkbox] {
        visibility: visible;
    }
</style>


<div id="content">

    <div class="inner">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Category</h1>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="box dark">
                    <header>
                        <div class="icons"><i class="icon-edit"></i></div>
                        <h5>Category</h5>

                    </header>
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="panel-body message">
                                <div class="alert alert-success">
                                    @ViewBag.ResultMessage
                                </div>
                            </div>
                        </div>
                    </div>

                    <div id="div-1" class="accordion-body collapse in body">

                        @using (Html.BeginForm("Create", "Category", FormMethod.Post, new { @id = "category_form", enctype = "multipart/form-data", @class = "form-horizontal" }))
                        {
                            @Html.AntiForgeryToken()
                            @Html.ValidationSummary(true)
                            <div class="form-group">
                                <label for="text1" class="control-label col-lg-4">Category Name *</label>
                                <div class="col-lg-6">
                                    @*<input type="text" id="text1" placeholder="Email" class="form-control" />*@
                                    @Html.TextBoxFor(model => model.Name, new { placeholder = "Category Name", required = "required", @class = "form-control" })
                                </div>
                                <div class="col-lg-2">
                                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="text1" class="control-label col-lg-4">Meta keyword *</label>

                                <div class="col-lg-6">
                                    @Html.TextBoxFor(model => model.MetaKeyword, new { placeholder = "Meta keyword", @required = "required", @class = "form-control" })
                                </div>
                                <div class="col-lg-2">
                                    @Html.ValidationMessageFor(model => model.MetaKeyword, "", new { @class = "danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="text1" class="control-label col-lg-4">Meta Description *</label>
                                <div class="col-lg-6">
                                    @Html.TextBoxFor(model => model.MetaDescription, new { placeholder = "Meta Description", @required = "required", @class = "form-control" })
                                </div>
                                <div class="col-lg-2">
                                    @Html.ValidationMessageFor(model => model.MetaDescription, "", new { @class = "danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="text1" class="control-label col-lg-4">Meta Title *</label>
                                <div class="col-lg-6">
                                    @Html.TextBoxFor(model => model.MetaTitle, new { placeholder = "Meta Title", @required = "required", @class = "form-control" })
                                </div>
                                <div class="col-lg-2">
                                    @Html.ValidationMessageFor(model => model.MetaTitle, "", new { @class = "danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="control-label col-lg-4">Select Category</label>
                                <div class="col-lg-6">
                                    @{List<SelectListItem> obj = ViewBag.ParentCategoryId;}
                                    @if (obj.Count != 0)
                                    {
                                        @Html.DropDownList("ParentCategoryId", obj, "[None]", new { @class = "form-control chzn-select" })
                                    }
                                </div>
                                <div class="col-lg-2">
                                    @Html.ValidationMessageFor(model => model.ParentCategoryId, "", new { @class = "danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="control-label col-lg-4">IsActive</label>
                                <div class="col-lg-6">
                                    @Html.CheckBoxFor(model => model.Published, new { @checked = "checked" })
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="control-label col-lg-4">Upload Category</label>
                                <div class="col-lg-6">
                                    <input type="file" name="Image" id="uploadEditorImage">
                                </div>

                            </div>
                            <div class="form-group">
                                <label for="pass1" class="control-label col-lg-4">&nbsp;</label>

                                <div class="col-lg-6">
                                    <input class="btn btn-primary btn-round" type="button" value="Save" onclick="Create('/Category/Create', '#category_form')" />
                                </div>
                            </div>
                        }
                    </div>
                </div>

            </div>
        </div>
    </div>

</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MyShop/MyShop/Views/Category/EditCategories.cshtml
@model  MyShop.Category


<link rel="stylesheet" href="/assets/plugins/chosen/chosen.min.css" />
<script src="/assets/plugins/chosen/chosen.jquery.min.js"></script>

<script type="text/javascript" src="~/assets/developer_js/Category.js"></script>
<script>
    $(document).ready(function () {
        $(".message").hide();

    })
</script>


<div id="content">

    <div class="inner">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Category</h1>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="box dark">
                    <header>
                        <div class="icons"><i class="icon-edit"></i></div>
                        <h5>Category Edit</h5>

                    </header>
                    <div class="panel-body message">
                        <div class="alert alert-success">

                        </div>
                    </div>



                    <div id="div-1" class="accordion-body collapse in body">

                        @using (Html.BeginForm("Create", "Category", FormMethod.Post, new { @id = "category_form", @class = "form-horizontal" }))
                        {
                            @Html.AntiForgeryToken()
                            @Html.ValidationSummary(true)
                            @Html.HiddenFor(model => model.CreatedOnUtc)
                            @Html.HiddenFor(model => model.ID)
                            @Html.HiddenFor(model => model.UpdatedOnUtc)
                            <div class="form-group">
                                <label for="text1" class="control-label col-lg-4">Category Name *</label>

                                <div class="col-lg-8">
                                    @*<input type="text" id="text1" placeholder="Email" class="form-control" />*@
                                    @Html.TextBoxFor(model => model.Name, new { placeholder = "Category Name", @required = "required", @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.Name)

                                </div>
                            </div>

                            <div class="form-group">
                                <label class="control-label col-lg-4">Select Sub Category</label>
                                <div class="col-lg-8">
                                    @{List<SelectListItem> obj = ViewBag.ParentCategoryId;}
                                    @*@Html.DropDownList("ParentCategoryId", obj, "[None]", new { @class = "form-control chzn-select" })*@
                                    <select class="form-control chzn-select">
                                        @for (int i = 0; i < obj.Count; i++)
                                        {
                                            if (obj[i].Selected == true)
                                            {
                                                <option value="@obj[i].Value" selected="selected">@obj[i].Text</option>
                                            }
                                            else
                                            {

                                                <option value="@obj[i].Value">@obj[i].Text</option>
                                            }
                                        }
                                    </select>
                                    @Html.ValidationMessageFor(model => model.ParentCategoryId)
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="text1" class="control-label col-lg-4">Meta keyword *</label>
                                <div class="col-lg-8">
                                    @Html.TextBoxFor(model => model.MetaKeyword, new { placeholder = "Meta keyword", @required = "required", @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.MetaKeyword)
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="text1" class="control-label col-lg-4">Meta Description *</label>
                                <div class="col-lg-8">
                                    @Html.TextBoxFor(model => model.MetaDescription, new { placeholder = "Meta Description", @required = "required", @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.MetaDescription)
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="text1" class="control-label col-lg-4">Meta Title *</label>
                                <div class="col-lg-8">
                                    @Html.TextBoxFor(model => model.MetaTitle, new { placeholder = "Meta Title", @required = "required", @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.MetaTitle)
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="control-label col-lg-4">IsActive</label>
                                <div class="col-lg-8">
                                    @Html.CheckBoxFor(model => model.Published, new { value = "None", @id = "squaredOne", name = "check" })
                                    @* it made a designer check box by this code
                                            <div class="squaredOne">
                                            <input type="checkbox" value="None" id="squaredOne" name="check" />

                                            @Html.CheckBoxFor(model => model.Published, new { value = "None", @id = "squaredOne", name = "check" })
                                            <label for="squaredOne"></label>
                                        </div>*@
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="control-label col-lg-4">Upload Category</label>
                                <div class="col-lg-6">
                                    <img src="~/Images/@Model.PictureName" height="50px" width="100px"/>
                                    <input type="file" name="Image">
                                </div>

                            </div>
                            <div class="form-group">

                                <div class="col-lg-8 pull-right">
                                    <input class="btn btn-primary btn-lg btn-width" type="button" value="Create" onclick="Update('/Category/EditCategories', '#role_form')" />
                                </div>
                            </div>
                        }
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

MyShop/MyShop/Views/Category/Index.cshtml
@model  IEnumerable<MyShop.Category> 
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<script type="text/javascript" src="~/assets/developer_js/Category.js"></script>

<div id="showpage">
</div>

<div id="indexpage">


    <!--PAGE CONTENT -->
    <div id="content">

        <div class="inner">
            <div class="row">
                <div class="col-lg-12">
                    <h2> Category  </h2>
                </div>
            </div>
            <hr />
            <div class="row">
                <div class="col-lg-12">
                    <div class="box dark">
                        <header>
                            <a href="#" onclick="CreatePage('/Category/Create')">
                                <div class="icons">
                                    <i class="icon-edit">
                                    </i>
                                </div>
                            </a>
                            <h5>Category Index Page</h5>
                        </header>
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                    <thead>
                                        <tr>
                                            <th>Category</th>
                                            @*<th>SubCategory</th>*@
                                            @*<th>Date</th>*@
                                            <th>IsActive</th>
                                            <th>Edit</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var Category in Model)
                                        {
                                            <tr class="odd gradeX">
                                                <td>@Category.Name</td>
                                                @*<td>@Category.ParentCategoryId</td>
                                                <td>@Category.PictureName</td>*@
                                                <td>@Category.Published</td>
                                                @*<td>@Html.ActionLink("Edit", "EditCategories", new { id = @Category.ID })</td>*@
                                                <td><a href="#" onclick="EditData('/Category/EditCategories',@Category.ID)">Edit</a></td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--END PAGE CONTENT -->

</div>