MyShop/MyShop/Models/Product/Product.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using MyShop;

namespace MyShop
{
    public class Product
    {

        public int id { get; set; }
       
        [Required(ErrorMessage = "*")]
        public string productName { get; set; }

        public string shortDescription { get; set; }

        public string fullDescription { get; set; }

        [Required(ErrorMessage = "*")]
        public decimal price { get; set; }

        public decimal? oldPrice { get; set; }

        // added this field later

        //[Required]
        //public int vendorID { get; set; }
        //public virtual Vendor vendor { get; set; }

        //[Required]
        //public int pictureID { get; set; }
        //public virtual Picture picture { get; set; }

        //public List<Picture> lstPicture = new List<Picture>();

        [Required]
        public int categoryID { get; set; }
        public virtual Category category { get; set; }

        [Required]
        public int manufucturersID { get; set; }
        public virtual Manufucturers manufucturers { get; set; }

        //public bool displayStockAvailability { get; set; }

        //public bool displayStockQuantity { get; set; }

        //public bool isTaxExempt { get; set; }

        //public int? taxCategoryId { get; set; }

        public string metaKeywords { get; set; }

        public string metaDescription { get; set; }

        public string metaTitle { get; set; }

        //public bool allowCustomerReviews { get; set; }

        //public string availableStartDisDateTimeUtc { get; set; }

        //public string availableEndDisDateTimeUtc { get; set; }

        //public string sku { get; set; }

        //public bool isGiftCard { get; set; }

        //public int? giftCardTypeId { get; set; }

        //public bool isDownload { get; set; }

        //public int? downloadId { get; set; }

        //public bool isFreeShippment { get; set; }

        //public int? shippingCharge { get; set; }

        //public int? deliveryDateId { get; set; }

        //public decimal? weight { get; set; }

        //public decimal? length { get; set; }

        //public decimal? width { get; set; }

        //public decimal? height { get; set; }

        public bool published { get; set; }

        //public int? stockQuantity { get; set; }

        //public bool hasDiscountsApplied { get; set; }

        //public decimal? discounts { get; set; }

        [DataType(DataType.Date)]
        public DateTime createdOnUtc { get; set; }

        [DataType(DataType.Date)]
        public DateTime updatedOnUtc { get; set; }



    }
}

MyShop/MyShop/Models/Product/ProductAttribute.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using MyShop;

namespace MyShop
{
    public class ProductAttribute
    {
        public int id { get; set; }

        [Required(ErrorMessage = "*")]
        public string name { get; set; }

        [Required]
        public int productAttributeOptionsID { get; set; }
        public virtual ProductAttributeOptions productAttributeOptions { get; set; }

        public string description { get; set; }

        public int categoryId { get; set; }
    }
}

MyShop/MyShop/Models/Product/ProductAttributeOptions.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace MyShop
{
    public class ProductAttributeOptions
    {
        public int id { get; set; }

        [Required(ErrorMessage = "*")]
        public string name { get; set; }
    }
}

MyShop/MyShop/Models/Product/ProductReview.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using MyShop;
namespace MyShop
{
    public class ProductReview
    {
        public int ID { get; set; }

        [Required]
        public int productID { get; set; }
        public virtual Product product { get; set; }
         
        //[Required]
        //public int CustomerDetailID { get; set; }
        //public virtual CustomerDetail CustomerDetail { get; set; }

        public bool IsApproved { get; set; }

        [Required(ErrorMessage = "*")]
        public string Title { get; set; }

        [Required(ErrorMessage="*")]
        public string ReviewText { get; set; }

       //[Required(ErrorMessage = "*")]
        public decimal Rating { get; set; }


        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime CreatedOnUtc { get; set; }

       
    }
}

MyShop/MyShop/Models/Product/ProductTag.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace G2MFashions.Models.Product
{
    public class ProductTag
    {
        public int ID { get; set; }
        public string Name { get; set; }
    }
}

MyShop/MyShop/Models/Product/ProductVariantAttributeValue.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
namespace MyShop
{
    public class ProductVariantAttributeValue
    {
        public int ID { get; set; }

        [Required]
        public int Product_ProductAttribute_MappingID { get; set; }
        public virtual Product_ProductAttribute_Mapping Product_ProductAttribute_Mapping { get; set; }

        public string Name { get; set; }

        public decimal PriceAdjustment { get; set; }

        public int Quentity { get; set; }

        public int PictureId { get; set; }
    }
}

MyShop/MyShop/Models/Product/Product_Category_Mapping.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using ModelLibrary.Category;
namespace MyShop
{
    public class Product_Category_Mapping
    {
        [ScaffoldColumn(false)]
        public int ID { get; set; }

        [Required]
        public int ProductID { get; set; }
        public virtual Product CustomerProduct { get; set; }

        [Required]
        public int CustomerCategoryID { get; set; }
        public virtual Category CustomerCategory { get; set; }

        public bool IsFeaturedProduct { get; set; }
    }
}

MyShop/MyShop/Models/Product/Product_Manufacturer_Mapping.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
//using G2MFashions.Models.Manufacturers;
using MyShop;
namespace MyShop
{
    public class Product_Manufacturer_Mapping
    {
        public int ID { get; set; }

        [Required]
        public int ProductID { get; set; }
        public virtual Product Product { get; set; }

        [Required]
        public int ManufucturersID { get; set; }
        public virtual Manufucturers Manufucturers { get; set; }
    }
}

MyShop/MyShop/Models/Product/Product_Picture_mapping.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace MyShop
{
    public class Product_Picture_mapping
    {
        [ScaffoldColumn(false)]
        public int id { get; set; }

        [Required]
        public int productID { get; set; }
        public virtual Product product { get; set; }

        [Required]
        public int pictureID { get; set; }
        public virtual Picture picture { get; set; }

        public  List<Picture> lstPicture = new List<Picture>();
        
    }
}

MyShop/MyShop/Models/Product/Product_ProductAttribute_Mapping.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
namespace MyShop
{
    public class Product_ProductAttribute_Mapping
    {
        //public int ID { get; set; }


        //[Required]
        //public int CustomerProductID { get; set; }
        //public virtual CustomerProduct CustomerProduct { get; set; }

        //[Required]
        //public int ProductAttributeID { get; set; }
        //public virtual ProductAttribute ProductAttribute { get; set; }

        //public int AttributeControlTypeId { get; set; }//?

        //public string ProductAttributevalue { get; set; }

        //public string TextPrompt { get; set; }

        //public bool IsRequired { get; set; }

        //public int DisplayOrder { get; set; }

    }
}

MyShop/MyShop/Models/Product/Product_ProductTag_Mapping.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
namespace MyShop
{
    public class Product_ProductTag_Mapping
    {
        //public int ID { get; set; }

        //[Required]
        //public int CustomerProductID { get; set; }
        //public virtual CustomerProduct CustomerProduct { get; set; }

        //[Required]
        //public int ProductTagID { get; set; }
        //public virtual ProductTag ProductTag { get; set; }
        
    }
}

MyShop/MyShop/Models/Product/Product_SpecificationAttribute_Mapping.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel;
using MyShop;
using System.ComponentModel.DataAnnotations;
namespace MyShop
{
    public class Product_SpecificationAttribute_Mapping
    {

        public int ID { get; set; }

        [Required]
        public int ProductID { get; set; }
        public virtual Product Product { get; set; }

        //[Required]
        //public int SpecificationAttributeID { get; set; }
        //public virtual SpecificationAttribute SpecificationAttribute { get; set; }

        public int SpecificationAttributeoptionid { get; set; }

        public bool AllowFiltering { get; set; }
                
        public bool ShowOnProductPage { get; set; }

    }
}

MyShop/MyShop/Controllers/Admin/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MyShop;
using MyShop.Models;
using System.IO;
using CommonMethod;

namespace MyShop.Controllers.Admin
{
    public class ProductsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Products
        public ActionResult Index()
        {
            var product = db.product.Include(p => p.category).Include(p => p.manufucturers);
            return View(product.ToList());
        }

        // GET: Products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            List<Product_Picture_mapping> productPictureMapping = db.productPicturemapping.Where(a => a.productID == id).Select(b => b).ToList();
            if (productPictureMapping == null)
            {
                return HttpNotFound();
            }
            return View(productPictureMapping);
        }

        // GET: Products/Create
        public ActionResult Create()
        {

            ViewBag.categoryID = new SelectList(db.Category, "ID", "Name");
            ViewBag.manufucturersID = new SelectList(db.manufucturers, "id", "name");
            return PartialView("Create");
        }

        #region Initialization
		 
        Picture picture = new Picture();
        List<int> pictureId = new List<int>();
        Product_Picture_mapping productPictureMapping = new Product_Picture_mapping();
        #endregion
        // POST: Products/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Product product, HttpPostedFileBase[] images, string PriorImage)
        {
            
            if (ModelState.IsValid)
            {
                product.createdOnUtc = DateTime.Now;
                product.updatedOnUtc = DateTime.Now;
                db.product.Add(product);
                db.SaveChanges();

                if (images.Length != 0 && product.id != 0)
                {
                    Product_Picture_mapping productPictureMapping = new Product_Picture_mapping();
                    picture = AddPicture(images,"Add");

                    productPictureMapping.productID = product.id;
                    foreach (int id in pictureId)
                    {
                        productPictureMapping.pictureID = id;
                        db.productPicturemapping.Add(productPictureMapping);
                        db.SaveChanges();
                    }
                }
                else
                {
                    ViewBag.message = Guideline.ImageAdd;
                }

                return RedirectToAction("Index");
            }

            ViewBag.categoryID = new SelectList(db.Category, "ID", "Name", product.categoryID);
            ViewBag.manufucturersID = new SelectList(db.manufucturers, "id", "name", product.manufucturersID);
            return View(product);
        }

        public Picture AddPicture(HttpPostedFileBase[] images,string status)
        {
            foreach (var image in images)
            {
                string fileName = Path.Combine(Server.MapPath("~/UserImage/"), image.FileName);
                image.SaveAs(fileName);
                picture.pictureName = image.FileName;
                picture.mimeType = image.ContentType;
                picture.seoFileName = "test_seo";
                if(status=="Add")
                db.picture.Add(picture);
                if (status == "Update")
                    db.Entry(picture).State = EntityState.Modified;
                db.SaveChanges();
                pictureId.Add(picture.id);
            }
            return picture;

        }

        public HttpStatusCodeResult BadRequest()
        {
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        public HttpNotFoundResult ChekResult()
        {
            return HttpNotFound();
        }

        // GET: Products/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
                BadRequest();

            Product_Picture_mapping productPicturemapping = db.productPicturemapping.Where(a => a.product.id == id).Select(y => y).FirstOrDefault();
            productPicturemapping.lstPicture = new List<Picture>();
            productPicturemapping.lstPicture = db.productPicturemapping.Where(a => a.product.id == id).Select(y => y.picture).ToList();
            if (productPicturemapping == null)
                return HttpNotFound();

            ViewBag.categoryID = new SelectList(db.Category, "ID", "Name", productPicturemapping.product.categoryID);
            ViewBag.manufucturersID = new SelectList(db.manufucturers, "id", "name", productPicturemapping.product.manufucturersID);
            return View(productPicturemapping);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Product_Picture_mapping productPictureMapping, HttpPostedFileBase[] images)
        {

            if (ModelState.IsValid)
            {
               
                productPictureMapping.product.updatedOnUtc = DateTime.Now;
                db.Entry(productPictureMapping.product).State = EntityState.Modified;
                db.SaveChanges();

                if (images.Length != 0 && productPictureMapping.product.id != 0)
                {

                    picture = AddPicture(images,"Update");

                    productPictureMapping.productID = productPictureMapping.product.id;
                    foreach (int id in pictureId)
                    {
                        productPictureMapping.pictureID = id;
                        db.Entry(productPictureMapping.picture).State = EntityState.Modified;
                        db.SaveChanges();
                    }
                    ViewBag.message = Guideline.Update;

                }
                else
                {
                    ViewBag.message = Guideline.ImageAdd;
                }

            }
            ViewBag.categoryID = new SelectList(db.Category, "ID", "Name", productPictureMapping.product.categoryID);
            ViewBag.manufucturersID = new SelectList(db.manufucturers, "id", "name", productPictureMapping.product.manufucturersID);


            return View();
           
        }

        // GET: Products/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.product.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = db.product.Find(id);
            db.product.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MyShop/MyShop/Views/Products/Create.cshtml
@model MyShop.Product
@using System;


<link rel="stylesheet" href="~/assets/css/bootstrap-fileupload.min.css" />
<script type="text/javascript" src="~/assets/developer_js/ImageUpload.js"></script>
<link rel="stylesheet" href="~/assets/developer_css/ArrowTab.css" />

<div id="content">

    <div class="inner">

        <div class="row">
            <div class="col-lg-12">


                <div class="box primary">
                    <ul class="nav nav-pills">
                        <li class="active">
                            <a href="#Add-Product" data-toggle="tab"><span class="badge">1</span><strong>Add Product</strong><span class="chevron"></span></a>
                        </li>
                        <li>
                            <a href="#Seo" data-toggle="tab"><span class="badge">2</span>Seo<span class="chevron"></span></a>
                        </li>
                        <li>
                            <a href="#Image" data-toggle="tab"><span class="badge">3</span>Image<span class="chevron"></span></a>
                        </li>
                        <li>
                            <a href="#Brand-Mapping" data-toggle="tab"><span class="badge">4</span>Brand Mapping<span class="chevron"></span></a>
                        </li>
                    </ul>
                </div>
                <div class="tab-content">
                    @using (Html.BeginForm("Create", "Products", FormMethod.Post, new { @id = "product_form", enctype = "multipart/form-data", @class = "form-horizontal" }))
                    {

                        @Html.AntiForgeryToken();
                        @*@Html.HiddenFor(model => model.createdOnUtc, new { @value=DateTime.Now});
                            @Html.HiddenFor(model => model.updatedOnUtc, new { @value = DateTime.Now });*@

                        <div class="tab-pane fade in active" id="Add-Product">

                            <div class="form-group">
                                <label for="text1" class="control-label col-lg-2"> Brand </label>
                                <div class="col-lg-5">
                                    @Html.DropDownList("manufucturersID", (SelectList)ViewBag.manufucturersID, "--Select--", new { @class = "form-control", @Required = "Required" })
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="text1" class="control-label col-lg-2">Category Name </label>
                                <div class="col-lg-5">

                                    @Html.DropDownList("categoryID", (SelectList)ViewBag.categoryID, "--Select--", new { @class = "form-control", @Required = "Required" })
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="text1" class="control-label col-lg-2">Product Name</label>
                                <div class="col-lg-5">
                                    @Html.TextBoxFor(model => model.productName, new { placeholder = "Product Name", @required = "required", @class = "form-control capitalize" })
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="text1" class="control-label col-lg-2">Short Description</label>
                                <div class="col-lg-5">
                                    @Html.TextBoxFor(model => model.shortDescription, new { placeholder = "Short Description", @class = "form-control" })
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="text1" class="control-label col-lg-2">Meta Keywords</label>
                                <div class="col-lg-5">
                                    @Html.TextBoxFor(model => model.metaKeywords, new { placeholder = "Meta Keywords", @class = "form-control" })
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="text1" class="control-label col-lg-2">Meta Description</label>
                                <div class="col-lg-5">
                                    @Html.TextBoxFor(model => model.metaDescription, new { placeholder = "Meta Description", @class = "form-control" })
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="text1" class="control-label col-lg-2">Meta Title</label>
                                <div class="col-lg-5">
                                    @Html.TextBoxFor(model => model.metaTitle, new { placeholder = "Meta Title", @class = "form-control" })
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="text1" class="control-label col-lg-2">Price</label>
                                <div class="col-lg-5">
                                    @Html.TextBoxFor(model => model.price, new { placeholder = "Price", @required = "required", @class = "form-control" })
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="control-label col-lg-2">Image</label>
                                <div class="col-lg-8">
                                    <div class="fileupload fileupload-new" data-provides="fileupload" id="id1">

                                        <div>
                                            <span class="btn btn-file btn-primary" style="width: 492px;"><span @*class="fileupload-new"*@>Select image</span><input type="file" name="images" onchange="img1(this)" multiple accept='image/*' /></span>
                                        </div>
                                        <div class="controls" id="multipleimage">

                                        </div>


                                    </div>

                                </div>
                            </div>

                            <div class="form-group">
                                <label for="text1" class="control-label col-lg-2">Old Price</label>
                                <div class="col-lg-5">
                                    @Html.TextBoxFor(model => model.oldPrice, new { placeholder = "Old Price", @class = "form-control" })
                                </div>
                            </div>

                            <div id="div-1" class="accordion-body collapse in body">
                                <div class="form-group">
                                    <label class="control-label col-lg-2">Select Color</label>
                                    <div class="col-lg-5">
                                        <div class="make-switch" data-on="primary" data-off="info">
                                            <input type="color" style="width: 492px;" />
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div id="div-1" class="accordion-body collapse in body">
                                <div class="form-group">
                                    <label class="control-label col-lg-2">IsActive</label>
                                    <div class="col-lg-5">
                                        <div class="make-switch" data-on="primary" data-off="info">
                                            @Html.CheckBoxFor(model => model.published)
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="text1" class="control-label col-lg-2"></label>
                                <div class="col-lg-2">
                                    @*<input type="submit" class="btn btn-primary" value="Save" />*@
                                    
                                    <a href="#" class="btn btn-primary" onclick="Create()">Save</a>
                                </div>
                                <div class="col-lg-3">
                                    <a href="/Products/Index" class="btn btn-primary">Back</a>
                                 
                                </div>
                            </div>


                        </div>

                        <div class="tab-pane fade in active" id="Seo">
                            <div id="div-2" class="accordion-body collapse in body">

                            </div>
                        </div>

                        <div class="tab-pane fade in active" id="Image">


                        </div>

                        <div class="tab-pane fade in active" id="Brand-Mapping">
                            <div id="div-4" class="accordion-body collapse in body">

                            </div>
                        </div>
                    }

                </div>

            </div>
        </div>
    </div>

</div>