MyShop/MyShop/Controllers/Admin/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyShop.Models;

namespace MyShop.Controllers.Admin
{
    public class RolesController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();
        #region Roles
        public ActionResult Index()
        {
            var roles = db.Roles.ToList();
            return View(roles);
        }

        public ActionResult Create()
        {
            return PartialView("Create");
        }

        [HttpPost]
        public ActionResult Create(string RoleName)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var thisRole = db.Roles.Where(r => r.Name.Equals(RoleName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();

                    if (thisRole == null)
                    {
                        db.Roles.Add(new Microsoft.AspNet.Identity.EntityFramework.IdentityRole()
                        {
                            Id = Guid.NewGuid().ToString(),
                            Name = RoleName
                        });
                        db.SaveChanges();
                        ViewBag.ResultMessage = "Role created successfully !";
                    }

                    else
                    {
                        ViewBag.ResultMessage = "Role already exist.";
                    }


                    return Json(new { message = ViewBag.ResultMessage });
                }

                catch (Exception ex)
                {
                    throw new Exception(ex.Message);
                }
            }
            ViewBag.ResultMessage = "Name can't be empty.";
            return Json(new { message = ViewBag.ResultMessage });
        }

        public ActionResult DeleteRoles(string RoleName)
        {
            var thisRole = db.Roles.Where(r => r.Name.Equals(RoleName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();
            db.Roles.Remove(thisRole);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult EditRoles(string roleName)
        {
            var thisRole = db.Roles.Where(r => r.Name.Equals(roleName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();

            //return PartialView("EditRoles",thisRole);
            return View(thisRole);
        }

        //
        // POST: /Roles/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditRoles(Microsoft.AspNet.Identity.EntityFramework.IdentityRole role)
        {
            try
            {
                db.Entry(role).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                ViewBag.ResultMessage = "Role updated successfully.";
                return Json(new { message = ViewBag.ResultMessage });

            }
            catch
            {
                return View();
            }
        }

        //public ActionResult ManageUserRoles(string sortOrder, string currentFilter, string searchString, int? page)
        //{

        //    ViewBag.CurrentSort = sortOrder;
        //    ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
        //    ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
            
        //    if (searchString != null)
        //    {
        //        page = 1;
        //    }
        //    else
        //    {
        //        searchString = currentFilter;
        //    }

        //    ViewBag.CurrentFilter = searchString;
        //    List<RoleList> roleobj = new List<RoleList>();
        //    var account = new AccountController();
        //    var user = db1.Users.ToList();
        //    foreach (var userid in user)
        //    {
        //        var data = account.UserManager.GetRoles(userid.Id);
        //        if (data.Count != 0)
        //        {
        //            roleobj.Add(new RoleList { ID = userid.Id, RoleName = data[0], CustomerName = userid.UserName });
        //        }
        //        else
        //        {
        //            roleobj.Add(new RoleList { ID = userid.Id, RoleName = "Not Assign", CustomerName = userid.UserName });
        //        }
        //        //ViewBag.ShowCustomerRole = roleobj;
        //    }

        //    var students = roleobj;
        //    if (!String.IsNullOrEmpty(searchString))
        //    {
        //        students = students.Where(s => s.CustomerName.Contains(searchString)).ToList();

        //    }
        //    switch (sortOrder)
        //    {
        //        case "name_desc":
        //            students = students.OrderByDescending(s => s.CustomerName).ToList();
        //            break;
        //        default:  // Name ascending 
        //            students = students.OrderBy(s => s.CustomerName).ToList();
        //            break;
        //    }

        //    int pageSize = 3;
        //    int pageNumber = (page ?? 1);
        //    return View(students.ToPagedList(pageNumber, pageSize));

        //}
        #endregion

    }
}

MyShop/MyShop/Views/Roles/Create.cshtml
@model Microsoft.AspNet.Identity.EntityFramework.IdentityRole
@*@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}*@



<script type="text/javascript" src="~/assets/developer_js/RolesScript.js"></script>

<script>
    $(document).ready(function () {
        $(".message").hide();
      
    })
</script>
    
<div id="content">

    <div class="inner">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">User Roles</h1>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="box dark">
                    <header>
                        <div class="icons"><i class="icon-edit"></i></div>
                        <h5>Roles</h5>
                      
                    </header>
                    <div class="panel-body message">
                        <div class="alert alert-success">
                         
                        </div>
                    </div>



                        <div id="div-1" class="accordion-body collapse in body">

                            @using (Html.BeginForm("Create", "Roles", FormMethod.Post, new { @id = "role_form", @class = "form-horizontal" }))
                            {
                                @Html.AntiForgeryToken()
                                @Html.ValidationSummary(true)

                                <div class="form-group">
                                    <label for="text1" class="control-label col-lg-4">Role Name</label>

                                    <div class="col-lg-8">
                                        @*<input type="text" id="text1" placeholder="Email" class="form-control" />*@
                                        @Html.TextBoxFor(model=>model.Name,new { placeholder = "Role Name",@required="required", @class = "form-control" })
                                        @Html.ValidationMessageFor(model=>model.Name)

                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="pass1" class="control-label col-lg-4">Create</label>

                                    <div class="col-lg-8">
                                        <input class="form-control" type="button" value="create" onclick="Create()" />
                                    </div>
                                </div>

                            }
                        </div>
                    </div>
            </div>

        </div>
    </div>
</div>

MyShop/MyShop/Views/Roles/EditRoles.cshtml
@model Microsoft.AspNet.Identity.EntityFramework.IdentityRole
@{
    ViewBag.Title = "EditRoles";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<script type="text/javascript" src="~/assets/developer_js/RolesScript.js"></script>
<script>
    $(document).ready(function () {
        $(".message").hide();

    })
</script>

<div id="content">

    <div class="inner">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Roles</h1>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="box dark">
                    <header>
                        <div class="icons"><i class="icon-edit"></i></div>
                        <h5>Edit Roles</h5>

                    </header>
                    <div class="panel-body message">
                        <div class="alert alert-success">

                        </div>
                 </div>
                    <div id="div-1" class="accordion-body collapse in body">

                        @using(Html.BeginForm("EditRoles", "Roles", FormMethod.Post, new { @id = "role_form", @class = "form-horizontal" }))
                        {
                            @Html.AntiForgeryToken()
                            @Html.ValidationSummary(true)
                            @Html.HiddenFor(model => model.Id)
                            <div class="form-group">
                                <label for="text1" class="control-label col-lg-4">Role Name</label>

                                <div class="col-lg-8">
                                    @*<input type="text" id="text1" placeholder="Email" class="form-control" />*@
                                    @Html.TextBoxFor(model=>model.Name, new { placeholder = "Role Name", @class = "validate[required] form-control" })
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="pass1" class="control-label col-lg-4">Edit</label>

                                <div class="col-lg-8">
                                    <input class="form-control" type="button" value="update" onclick="Update()" />
                                </div>
                            </div>

                        }
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

MyShop/MyShop/Views/Roles/Index.cshtml
@model IEnumerable<Microsoft.AspNet.Identity.EntityFramework.IdentityRole>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<script type="text/javascript" src="~/assets/developer_js/RolesScript.js"></script>

<div id="showpage">
</div>

<div id="indexpage">


    <!--PAGE CONTENT -->
    <div id="content">

        <div class="inner">
            <div class="row">
                <div class="col-lg-12">


                    <h2> Roles  </h2>



                </div>
            </div>

            <hr />


            <div class="row">
                <div class="col-lg-12">
                    <div class="box dark">

                        <header>
                            <a href="#" onclick="CreatePage()">
                                <div class="icons">
                                    <i class="icon-edit">
                                    </i>
                                </div>
                            </a>
                            <h5>Roles Index Page</h5>

                        </header>

                        <div class="panel-body">
                            <div class="table-responsive">
                                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                    <thead>
                                        <tr>
                                            <th>Name</th>
                                            <th>Edit</th>

                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var role in Model)
                                        {
                                            <tr class="odd gradeX">
                                                <td>@role.Name</td>
                                                <td>@Html.ActionLink("Edit", "EditRoles", new { roleName = @role.Name })</td>

                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>

                        </div>
                    </div>
                </div>
            </div>


        </div>




    </div>
    <!--END PAGE CONTENT -->

</div>